version: '3'

services:
  # PHP Service
  app:
    image: php:8.2.4
    container_name: yousseffarni_api
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    depends_on:
      - mysql
    networks:
      - laravel

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: laravel-nginx
    ports:
      - "8000:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

  # MySQL Service
  mysql:
    image: mysql:5.7
    container_name: yousseffarni_api
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: if0_35407594_portfolio_youssef
      MYSQL_USER: if0_35407594
      MYSQL_PASSWORD: LbfKL4sWV3
      MYSQL_ROOT_PASSWORD: secret
    networks:
      - laravel

networks:
  laravel:
